### ISSUE TITLE
Duplicate sequence when saving to disk

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1401]
**Describe the bug**
I was filling one of my forgers (zillion) transaction pool with ~1000 transactions to see what will happen and I was missing blocks and got this error:

&gt; 0|ark-core | [2018-11-15 18:25:46][INFO] : Block download finished :rocket:
0|ark-core | [2018-11-15 18:25:46][DEBUG] : event 'PROCESSFINISHED': {"syncWithNetwork":"downloadFinished"} -&gt; {"syncWithNetwork":"processFinished"} -&gt; actions: [{"type":"checkLastBlockSynced"}]
0|ark-core | [2018-11-15 18:25:46][DEBUG] : event 'SYNCED': {"syncWithNetwork":"processFinished"} -&gt; {"syncWithNetwork":"end"} -&gt; actions: [{"type":"syncingComplete"}]
0|ark-core | [2018-11-15 18:25:46][INFO] : Blockchain 100% in sync :100:
0|ark-core | [2018-11-15 18:25:46][DEBUG] : event 'SYNCFINISHED': {"syncWithNetwork":"end"} -&gt; "idle" -&gt; actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
0|ark-core | [2018-11-15 18:25:47][INFO] : Block 755,453 pinged blockchain 27 times
0|ark-core | [2018-11-15 18:25:47][INFO] : Received new block at height 755,454 with 0 transactions from 167.114.43.44
0|ark-core | [2018-11-15 18:25:47][DEBUG] : Delegate genesis_41 (02637b15aa50fa95018609a6d7b52b025de807a41b79b164626cee87dd6f61a662) allowed to forge block 755,454 :+1:
0|ark-core | [2018-11-15 18:25:47][DEBUG] : event 'PROCESSFINISHED': "newBlock" -&gt; "idle" -&gt; actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
0|ark-core | [2018-11-15 18:25:47][INFO] : Broadcasting block 755,454 to 49 peers
0|ark-core | [2018-11-15 18:25:54][INFO] : Checking 74 peers :telescope:
0|ark-core | [2018-11-15 18:25:54][INFO] : Received new block at height 755,455 with 200 transactions from 127.0.0.1
0|ark-core | [2018-11-15 18:25:54][DEBUG] : Delegate zillion (0366da7ed85cc1e73a13fafb8007d2609d92239355847343cc7b12d85a65d25502) allowed to forge block 755,455 :+1:
0|ark-core | [2018-11-15 18:25:55][DEBUG] : SqliteError: cannot start a transaction within a transaction
0|ark-core | at Storage.bulkAdd (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/storage.js:56:31)
0|ark-core | at TransactionPool.__syncToPersistentStorage (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:420:18)
0|ark-core | at TransactionPool.__syncToPersistentStorageIfNecessary (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:411:12)
0|ark-core | at TransactionPool.removeTransactionById (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:135:10)
0|ark-core | at TransactionPool.removeTransaction (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:123:10)
0|ark-core | at TransactionPool.acceptChainedBlock (/home/darknodeuser/ark-core/packages/core-transaction-pool/lib/interface.js:247:14)
0|ark-core | at Blockchain.acceptChainedBlock (/home/darknodeuser/ark-core/packages/core-blockchain/lib/blockchain.js:464:30)
0|ark-core | [2018-11-15 18:25:55][INFO] : Broadcasting block 755,455 to 74 peers
0|ark-core | [2018-11-15 18:25:55][DEBUG] : event 'PROCESSFINISHED': "newBlock" -&gt; "idle" -&gt; actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
0|ark-core | [2018-11-15 18:26:01][DEBUG] : 144.202.75.170 still suspended for a few seconds because of "Blockchain not ready".
0|ark-core | [2018-11-15 18:26:11][INFO] : Block 755,454 pinged blockchain 24 times
0|ark-core | [2018-11-15 18:26:11][INFO] : Received new block at height 755,456 with 0 transactions from 94.16.113.187
0|ark-core | [2018-11-15 18:26:11][DEBUG] : Delegate starshot (02a1b28b59216ea270349c6be5881fba356cb324f320cb59b74a13f28588cce253) allowed to forge block 755,456 :+1:
0|ark-core | [2018-11-15 18:26:11][DEBUG] : event 'FORK': "newBlock" -&gt; {"fork":"analysing"} -&gt; actions: [{"type":"startForkRecovery"},{"type":"analyseFork"}]
0|ark-core | [2018-11-15 18:26:11][INFO] : Starting fork recovery :fork_and_knife:
0|ark-core | [2018-11-15 18:26:11][INFO] : Analysing fork :mag:
0|ark-core | [2018-11-15 18:26:11][INFO] : Removing 35 blocks. Reset to height 755,420
0|ark-core | [2018-11-15 18:26:11][INFO] : Undoing block 755,455
0|ark-core | [2018-11-15 18:26:11][DEBUG] : Transaction pool: ignoring attempt to add a transaction that is already in the pool, id: c8a79b642c57222fbcfdb0fa8de15382d40c8fdc695b181e2e259c40b02d6777
0|ark-core | [2018-11-15 18:26:11][DEBUG] : Transaction pool: ignoring attempt to add a transaction that is already in the pool, id: cbfd531c88be482ec4e59d6b9989d9f79cf288cdbf574b571a91baf8a1d817c1
0|ark-core | [2018-11-15 18:26:11][DEBUG] : Transaction pool: ignoring attempt to add a transaction that is already in the pool, id: ce02789caddf97d95725de7d17fc2799e7c890b06bf648de9fb284449f08c9e2

**Server (please complete the following information):**

* OS: Ubuntu
* Version: 18.04

**Comment by vasild** [comment]
Which version of the software were you running?
Is this reproducable or it happened just once?

**Comment by vasild** [comment]
This is the relevant code:
```
 50     const insertStatement = this.db.prepare(
 51       `INSERT INTO ${this.table} ` +
 52         '(sequence, id, serialized, ping_count) VALUES ' +
 53         '(:sequence, :id, :serialized, :pingCount);',
 54     )
 55 
 56     this.db.prepare('BEGIN;').run()
 57 
 58     data.forEach(d =>
 59       insertStatement.run({
 60         sequence: d.sequence,
 61         id: d.transaction.id,
 62         serialized: Buffer.from(d.transaction.serialized, 'hex'),
 63         pingCount: d.pingCount,
 64       }),
 65     )
 66 
 67     this.db.prepare('COMMIT;').run()
```

It is synchronous and always does COMMIT at the end. Nodejs is executing it in a single OS thread. The only way I can think of that could lead to executing BEGIN after another BEGIN without a COMMIT is that if the INSERT or the COMMIT itself throws an exception, some higher code catches it and continues execution.

That said, if this threw an exception, there should be some trace of it in the logs before the "cannot start a transaction within a transaction" error. Do you have the _full_ log?

**Comment by zillionn** [comment]
> $ cat 2018-11-15.log |grep SqliteError
[2018-11-15 12:49:24][DEBUG]                      : SqliteError: UNIQUE constraint failed: pool.sequence
[2018-11-15 16:22:01][DEBUG]                      : SqliteError: cannot start a transaction within a transaction
[2018-11-15 18:25:55][DEBUG]                      : SqliteError: cannot start a transaction within a transaction
[2018-11-15 19:26:57][DEBUG]                      : SqliteError: cannot start a transaction within a transaction
[2018-11-15 23:10:08][DEBUG]                      : SqliteError: cannot start a transaction within a transaction

Attaching the full log from 15th.

[2018-11-15.log.zip](https://github.com/ArkEcosystem/core/files/2589069/2018-11-15.log.zip)

**Comment by zillionn** [comment]
I'm using the latest version.

**Comment by zillionn** [comment]
Are you sure it's synchronous?
https://github.com/mapbox/node-sqlite3/wiki/Control-Flow

**Comment by vasild** [comment]
> Are you sure it's synchronous?
> https://github.com/mapbox/node-sqlite3/wiki/Control-Flow

We are using https://www.npmjs.com/package/better-sqlite3

**Comment by vasild** [comment]
> The only way I can think of that could lead to executing BEGIN after another BEGIN without a COMMIT is that if the INSERT or the COMMIT itself throws an exception, some higher code catches it and continues execution.

> [2018-11-15 12:49:24][DEBUG] : SqliteError: UNIQUE constraint failed: pool.sequence
> [2018-11-15 16:22:01][DEBUG] : SqliteError: cannot start a transaction within a transaction

So, most likely, this is what happens - the insert throws an exception because of unique constraint violation and the commit is never executed. Two things to do:
1. Investigate why we end up with duplicate `sequence`
2. See if there is [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) for JavaScript to elegantly call commit whenever that function completes

**Comment by zillionn** [comment]
It's happening almost every time for me.

> 0|ark-core-relay  | [2018-11-16 14:49:40][INFO]                       : Downloading blocks from height 763,162 via 178.32.227.48
0|ark-core-relay  | [2018-11-16 14:49:40][INFO]                       : No new block found on this peer
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : event 'NOBLOCK': {"syncWithNetwork":"downloadBlocks"} -> {"syncWithNetwork":"syncing"} -> actions: [{"type":"checkLastDownloadedBlockSynced"}]
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : Queued blocks for rebuildQueue: 0
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : Queued blocks for processQueue: 0
0|ark-core-relay  | [2018-11-16 14:49:40][INFO]                       : Tried to sync 5 times to different nodes, looks like the network is missing blocks ☔️
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : event 'NETWORKHALTED': {"syncWithNetwork":"syncing"} -> {"syncWithNetwork":"end"} -> actions: [{"type":"syncingComplete"}]
0|ark-core-relay  | [2018-11-16 14:49:40][INFO]                       : Blockchain 100% in sync 💯
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : event 'SYNCFINISHED': {"syncWithNetwork":"end"} -> "idle" -> actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
1|ark-core-forger | [2018-11-16 14:49:40][INFO]                       : Forged new block 11994024777931210559 by delegate zillion (0366da7ed85cc1e73a13fafb8007d2609d92239355847343cc7b12d85a65d25502) 🔱
1|ark-core-forger | [2018-11-16 14:49:40][DEBUG]                      : Broadcasting forged block id:11994024777931210559 at height:763,163 with 150 transactions to http://127.0.0.1:4002 📦
0|ark-core-relay  | [2018-11-16 14:49:40][INFO]                       : Received new block at height 763,163 with 150 transactions from 127.0.0.1
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : Delegate zillion (0366da7ed85cc1e73a13fafb8007d2609d92239355847343cc7b12d85a65d25502) allowed to forge block 763,163 👍
0|ark-core-relay  | [2018-11-16 14:49:40][WARN]                       : Issue applying block to transaction pool
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : SqliteError: cannot start a transaction within a transaction
0|ark-core-relay  |     at Storage.bulkAdd (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/storage.js:56:31)
0|ark-core-relay  |     at TransactionPool.__syncToPersistentStorage (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:420:18)
0|ark-core-relay  |     at TransactionPool.__syncToPersistentStorageIfNecessary (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:411:12)
0|ark-core-relay  |     at TransactionPool.removeTransactionById (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:135:10)
0|ark-core-relay  |     at TransactionPool.removeTransaction (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:123:10)
0|ark-core-relay  |     at TransactionPool.acceptChainedBlock (/home/darknodeuser/ark-core/packages/core-transaction-pool/lib/interface.js:247:14)
0|ark-core-relay  |     at Blockchain.acceptChainedBlock (/home/darknodeuser/ark-core/packages/core-blockchain/lib/blockchain.js:464:30)
0|ark-core-relay  | [2018-11-16 14:49:40][INFO]                       : Broadcasting block 763,163 to 54 peers
0|ark-core-relay  | [2018-11-16 14:49:40][DEBUG]                      : event 'PROCESSFINISHED': "newBlock" -> "idle" -> actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
0|ark-core-relay  | [2018-11-16 14:49:43][DEBUG]                      : 37.59.70.165 still suspended for 4 minutes because of "No Common Blocks".
0|ark-core-relay  | [2018-11-16 14:49:52][INFO]                       : Block 763,162 pinged blockchain 13 times
0|ark-core-relay  | [2018-11-16 14:49:52][INFO]                       : Received new block at height 763,164 with 0 transactions from 209.250.251.125
0|ark-core-relay  | [2018-11-16 14:49:52][DEBUG]                      : Delegate multiforger (03f294777f7376e970b2bd4805b4a90c8449b5935d530bdb566d02800ac44a4c00) allowed to forge block 763,164 👍
0|ark-core-relay  | [2018-11-16 14:49:52][INFO]                       : Starting Round 14,965 🕊
0|ark-core-relay  | [2018-11-16 14:49:52][DEBUG]                      : Updating delegate statistics

This is how to reproduce:
1. Whitelist your sender and start sending transactions to your node until you have >1000 in the pool:
`~/ark-core/packages/core-tester-cli/bin/tester transfer --skip-validation --base-url http://127.0.0.1 -p "sender passphrase" -a 0.00000001 --transfer-fee 0.00000270 -n 40 --smart-bridge 'spam'`

2. Check the unconfirmed API:
http://IP:4003/api/v2/transactions/unconfirmed
Also not sure why, but very often I sent 40 trxs but less are added to the pool, like 32 or sometimes just 1. This is happening when I already have some in the pool, mostly when >500. However, in the log I get `Received 40 new transactions`...

3. Wait until you forge a block or few

**Comment by vasild** [comment]
Hi, can you try to reproduce with the code in this pull request: https://github.com/ArkEcosystem/core/pull/1434 (branch `wip-chasing1401`)? I added some stricter checks that should expose the problem of duplicate `sequence` earlier.

Thanks!

**Comment by zillionn** [comment]
I'm trying but no such error yet.

You can try yourself:
1. Add your public key to `allowSenders`
2. Spam trxs like this:
~/ark-core/packages/core-tester-cli/bin/tester transfer --skip-validation --base-url http://127.0.0.1 -p "sender passphrase" -a 0.00000001 --transfer-fee 0.10000000 -n 40 --smart-bridge 'spam'
I'm sending the following command one after another for like 20-30 times.

I could be related to this issue #1421

**Comment by zillionn** [comment]
I got this now:

> [2018-11-19 19:50:43][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:43][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : Received 150 transactions from the pool containing 883 💸
[2018-11-19 19:50:44][INFO]                       : Forged new block 5640406008633165486 by delegate zillion (0366da7ed85cc1e73a13fafb8007d2609d92239355847343cc7b12d85a65d25502) 🔱
[2018-11-19 19:50:44][DEBUG]                      : Broadcasting forged block id:5640406008633165486 at height:785,219 with 150 transactions to http://127.0.0.1:4002 📦
[2018-11-19 19:50:44][INFO]                       : Received new block at height 785,219 with 150 transactions from 127.0.0.1
[2018-11-19 19:50:44][DEBUG]                      : Delegate zillion (0366da7ed85cc1e73a13fafb8007d2609d92239355847343cc7b12d85a65d25502) allowed to forge block 785,219 👍
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][WARN]                       : Issue applying block to transaction pool
[2018-11-19 19:50:44][DEBUG]                      : SqliteError: UNIQUE constraint failed: pool.sequence
    at data.forEach.d (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/storage.js:60:25)
    at Array.forEach (<anonymous>)
    at Storage.bulkAdd (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/storage.js:59:12)
    at TransactionPool.__syncToPersistentStorage (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:429:18)
    at TransactionPool.__syncToPersistentStorageIfNecessary (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:420:12)
    at TransactionPool.removeTransactionById (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:175:10)
    at TransactionPool.removeTransaction (/home/darknodeuser/ark-core/packages/core-transaction-pool-mem/lib/connection.js:163:10)
    at TransactionPool.acceptChainedBlock (/home/darknodeuser/ark-core/packages/core-transaction-pool/lib/interface.js:253:14)
    at Blockchain.acceptChainedBlock (/home/darknodeuser/ark-core/packages/core-blockchain/lib/blockchain.js:464:30)
[2018-11-19 19:50:44][INFO]                       : Broadcasting block 785,219 to 18 peers
[2018-11-19 19:50:44][DEBUG]                      : event 'PROCESSFINISHED': "newBlock" -> "idle" -> actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".
[2018-11-19 19:50:44][DEBUG]                      : 167.114.29.39 still suspended for a minute because of "Invalid Response Status".

**Comment by vasild** [comment]
We found one reason that for sure will cause this bug and it is fixed in https://github.com/ArkEcosystem/core/pull/1457 (thanks, @supaiku0 !)

**Comment by zillionn** [comment]
Great. Will reopen if I see the error again.

**Comment by zillionn** [comment]
I see the same error again multiple times. Attaching the log.
[2018-11-23.log.zip](https://github.com/ArkEcosystem/core/files/2610765/2018-11-23.log.zip)

This is before the latest updates from the last ~20 hours.

Also probably for another issue, it was not recovering from `Fork 6`. I've updated the core with the commander but it was still not recovering. After another manual restart, it synced.

**Comment by vasild** [comment]
@zillionn do you have f667c738?

It would be better if you can provide the commit id, instead of "latest" or "20 hours ago".

Thanks!

**Comment by kristjank** [comment]
what about today, can you try with fresh update to repeat this?

**Comment by kristjank** [comment]
like fresh install, default ENVs, remove old pool, remove logs - and repeat the hammering of your node? @zillionn  

and if it is again, we have fresh state with fresh logs, would help us move further with this issue. tnx

**Comment by zillionn** [comment]
After reinstall txs enter the pool. I'll reopen if I see `SqliteError ` again.
